<?php
//the entire function is essentially an INCLUDES, notably: require($file) through engine.php;

function messageContent($file) {
    ob_start();
    $ = $_POST['name'];
    $ = $_POST['other_previous_experience'];
    $ = $_POST['year_of_entry'];
    $ = $_POST['UF_ID'];
    $ = $_POST['suffix_name'];
    $ = $_POST['other_names'];
    $ = $_POST['sex'];
    $ = $_POST['date_of_birth'];
    $ = $_POST['city_of_birth'];
    $ = $_POST['state_of_birth'];
    $ = $_POST['country_of_birth'];
    $ = $_POST['citizenship'];
    $ = $_POST['street_address'];
    $ = $_POST['city_mailing'];
    $ = $_POST['state_mailing'];
    $ = $_POST['country_mailing'];
    $ = $_POST['zip_mailing'];
    $ = $_POST['street_permanent'];
    $ = $_POST['city_permanent'];
    $ = $_POST['state_permanent'];
    $ = $_POST['country_permanent'];
    $ = $_POST['zip_permanent'];
    $ = $_POST['email'];
    $ = $_POST['phone_home'];
    $ = $_POST['phone_mobile'];
    $ = $_POST['phone_work'];
    $ = $_POST['evaluator_one_name'];
    $ = $_POST['evaluator_one_street'];
    $ = $_POST['evaluator_one_city'];
    $ = $_POST['evaluator_one_state'];
    $ = $_POST['evaluator_one_zip'];
    $ = $_POST['evaluator_one_phone'];
    $ = $_POST['evaluator_one_email'];
    $ = $_POST['evaluator_two_name'];
    $ = $_POST['evaluator_two_street'];
    $ = $_POST['evaluator_two_city'];
    $ = $_POST['evaluator_two_state'];
    $ = $_POST['evaluator_two_zip'];
    $ = $_POST['evaluator_two_phone'];
    $ = $_POST['evaluator_two_email'];
    $ = $_POST['educational_background_one_institution'];
    $ = $_POST['educational_background_one_major'];
    $ = $_POST['educational_background_one_start_date'];
    $ = $_POST['educational_background_one_end_date'];
    $ = $_POST['educational_background_one_degree_earned'];
    $ = $_POST['educational_background_one_date_will_earn_degree'];
    $ = $_POST['educational_background_two_institution'];
    $ = $_POST['educational_background_two_major'];
    $ = $_POST['educational_background_two_start_date'];
    $ = $_POST['educational_background_two_end_date'];
    $ = $_POST['educational_background_two_degree_earned'];
    $ = $_POST['educational_background_two_date_will_earn_degree'];
    $ = $_POST['educational_background_three_institution'];
    $ = $_POST['educational_background_three_major'];
    $ = $_POST['educational_background_three_start_date'];
    $ = $_POST['educational_background_three_end_date'];
    $ = $_POST['educational_background_three_degree_earned'];
    $ = $_POST['educational_background_three_will_earn_degree'];
    $ = $_POST['educational_background_four_institutions'];
    $ = $_POST['educational_background_four_major'];
    $ = $_POST['educational_background_four_start_date'];
    $ = $_POST['educational_background_four_end_date'];
    $ = $_POST['educational_background_four_degree_earned'];
    $ = $_POST['educational_background_four_will_earn_degree'];
    $ = $_POST['standardized_tests_ACT'];
    $ = $_POST['standardized_tests_GMAT'];
    $ = $_POST['standardized_tests_GRE'];
    $ = $_POST['standardized_tests_MCAT'];
    $ = $_POST['standardized_tests_SAT'];
    $ = $_POST['standardized_tests_TOEFL'];
    $ = $_POST['standardized_tests_other'];
    $ = $_POST['explanation_previously_applied'];
    $ = $_POST['explanation_probation'];
    $ = $_POST['explanation_conviction'];
    $ = $_POST['volunteer_experience_one_organization'];
    $ = $_POST['volunteer_experience_one_contact_name'];
    $ = $_POST['volunteer_experience_one_contact_address'];
    $ = $_POST['volunteer_experience_one_dates'];
    $ = $_POST['volunteer_experience_one_duties'];
    $ = $_POST['volunteer_experience_two_organization'];
    $ = $_POST['volunteer_experience_two_contact_name'];
    $ = $_POST['volunteer_experience_two_contact_address'];
    $ = $_POST['volunteer_experience_two_dates'];
    $ = $_POST['volunteer_experience_two_duties'];
    $ = $_POST['volunteer_experience_three_organization'];
    $ = $_POST['volunteer_experience_three_contact_name'];
    $ = $_POST['volunteer_experience_three_contact_address'];
    $ = $_POST['volunteer_experience_three_dates'];
    $ = $_POST['volunteer_experience_three_duties'];
    $ = $_POST['volunteer_experience_four_organization'];
    $ = $_POST['volunteer_experience_four_contact_name'];
    $ = $_POST['volunteer_experience_four_contact_address'];
    $ = $_POST['volunteer_experience_four_dates'];
    $ = $_POST['volunteer_experience_four_duties'];
    $ = $_POST['essay_why_healthcare'];
    $ = $_POST['essay_qualities_strengths'];
    $ = $_POST['essay_why_interested'];
    $ = $_POST['essay_previous_grades'];
    $ = $_POST['essay_additional_information'];
    $ = $_POST['essay_how_you_know_phpb'];
    $ = $_POST['submit'];
    $css = file_get_contents("../../email/stylesheet.css");
    $set = "set.php setting in the email";
    require($file);
    return ob_get_clean();
}

include("engine.php");
?>
