To honor our award-winning faculty and students, we bestow Laurels upon those who receive major grant funding, fellowships, and national/international honors, and Kudos among those who are highly ranked in their field or marked with distinction for their work.
<h2>Recent Awards and Recognition</h2>
<ul class="orange">
 	<li><a href="https://publications.clas.ufl.edu/college-newsletter/heart-of-the-congo/">Nancy Rose Hunt Receives Guggenheim Fellowship</a></li>
 	<li><a href="https://publications.clas.ufl.edu/biology-newsletter/biology-spring-summer-2018/biology-student-wins-goldwater-scholarship/">Biology Student Wins Goldwater Scholarship</a></li>
</ul>
<ul class="orange">
 	<li><a href="https://publications.clas.ufl.edu/college-newsletter/las-summer-2018/student-profile-aaron-klein-18/">Speech and Debate Student Named Top Persuasive Speaker</a></li>
 	<li><a href="https://publications.clas.ufl.edu/college-newsletter/las-winter-2018/mock-trial-mavens/">The LitiGators placed 8th out of the 48 top teams at the American Mock Trial Association tournament</a></li>
</ul>

<hr />

<h2 style="text-align: center;">University Awards</h2>
The University of Florida recognizes excellence in teaching, advising, and research in several ways. In addition, top professors are named <a href="https://sites.clas.ufl.edu/clas-main/laurels-and-kudos/university-term-professors-2018/">University Term Professors</a> or <a href="https://sites.clas.ufl.edu/clas-main/laurels-and-kudos/uf-research-foundation-professors/">UF Research Foundation Professors</a>. &amp;amp;lt;Learn more about the University-level awards and meet their recipients in our college.
<div style="text-align: center;"><a class="btn-orange" href="https://sites.clas.ufl.edu/clas-main/laurels-and-kudos/university-term-professors-2018/">Meet the 2018 University Term Professors</a>
<a href="https://sites.clas.ufl.edu/clas-main/laurels-and-kudos/university-term-professors-2018/"><img class="aligncenter size-full wp-image-7848" src="https://sites.clas.ufl.edu/clas-main/files/2019/01/FotoJet.jpg" alt="" width="1200" height="1200" /></a></div>
<h2 style="text-align: center;">College Awards</h2>
The College of Liberal Arts and Sciences offers named <a href="https://sites.clas.ufl.edu/clas-main/laurels-and-kudos/college-term-professors/">Term Professorships</a> through private funding sources; in addition, it offers the Humanities Scholarship Enhancement Award to select faculty. <a href="https://sites.clas.ufl.edu/clas-main/laurels-and-kudos/humanities-scholarship-enhancement-award/">Meet the recipients</a> or <a href="https://dean.clas.ufl.edu/faculty-research-funding-travel/humanities-scholarship-enhancement-fund/">learn how to apply for the HSE Award</a>.
<div style="text-align: center;"><a class="btn-orange" href="https://sites.clas.ufl.edu/clas-main/laurels-and-kudos/university-term-professors-2018/">Meet the 2018 College Term Professors</a>
<a href="https://sites.clas.ufl.edu/clas-main/laurels-and-kudos/college-term-professors/"><img class="aligncenter size-full wp-image-7850" src="https://sites.clas.ufl.edu/clas-main/files/2019/01/FotoJet-1.jpg" alt="" width="1200" height="495" /></a></div>

<hr>

<div id="chairs">

  <h2 style="text-align: center;">Named Chairs</h2>
  <h3>Department Chairs</h3>
  <h4>Anthropology</h4><p><b>Peter Collings</b>&nbsp;&nbsp;<span class="email_chair">pcollings@ufl.edu</span></p><h4>Astronomy</h4><p><b>Elizabeth Lada</b>&nbsp;&nbsp;<span class="email_chair">elada@astro.ufl.edu</span></p><h4>Biology</h4><p><b>Marta Wayne</b>&nbsp;&nbsp;<span class="email_chair">chair@biology.ufl.edu</span></p><h4>Chemistry</h4><p><b>Lisa McElwee-White</b>&nbsp;&nbsp;<span class="email_chair">chair@chem.ufl.edu</span></p><h4>Classics</h4><p><b>Mary Ann Eaverly</b>&nbsp;&nbsp;<span class="email_chair">eaverly@ufl.edu</span></p><h4>Economics</h4><p><b>Thomas Knight</b>&nbsp;&nbsp;<span class="email_chair">thomas.knight@ufl.edu</span></p><h4>English</h4><p><b>Sid Dobrin</b>&nbsp;&nbsp;<span class="email_chair">sdobrin@ufl.edu</span></p><h4>Geography</h4><p><b>Jane Southworth</b>&nbsp;&nbsp;<span class="email_chair">jsouthwo@ufl.edu</span></p><h4>Geological Sciences</h4><p><b>David Foster</b>&nbsp;&nbsp;<span class="email_chair">dafoster@ufl.edu</span></p><h4>History</h4><p><b>Elizabeth Dale</b>&nbsp;&nbsp;<span class="email_chair">edale@ufl.edu</span></p><h4>Languages, Literatures &amp; Cultures</h4><p><b>Akintunde Akinyemi</b>&nbsp;&nbsp;<span class="email_chair">akinyemi@ufl.edu</span></p><h4>Linguistics</h4><p><b>Eric Potsdam</b>&nbsp;&nbsp;<span class="email_chair">potsdam@ufl.edu</span></p><h4>Mathematics</h4><p><b>Kevin Knudson</b>&nbsp;&nbsp;<span class="email_chair">kknudson@ufl.edu</span></p><h4>Philosophy</h4><p><b>John Palmer</b>&nbsp;&nbsp;<span class="email_chair">palmerj@ufl.edu</span></p><h4>Physics</h4><p><b>Kevin Ingersent</b>&nbsp;&nbsp;<span class="email_chair">ingersent@ufl.edu</span></p><h4>Political Science</h4><p><b>Dan Smith</b>&nbsp;&nbsp;<span class="email_chair">dasmith@ufl.edu</span></p><h4>Psychology</h4><p><b>Julie Graber</b>&nbsp;&nbsp;<span class="email_chair">jagraber@ufl.edu</span></p><h4>Religion</h4><p><b>Terje Ostebo</b>&nbsp;&nbsp;<span class="email_chair">ostebo@ufl.edu</span></p><h4>Sociology and Criminology &amp; Law</h4><p><b>Barbara Zsembik</b>&nbsp;&nbsp;<span class="email_chair">zsembik@ufl.edu</span></p><h4>Spanish &amp; Portuguese Studies</h4><p><b>Gillian Lord</b>&nbsp;&nbsp;<span class="email_chair">glord@ufl.edu</span></p><h4>Statistics</h4><p><b>Mike Daniels</b>&nbsp;&nbsp;<span class="email_chair">daniels@ufl.edu</span></p>

  <h3>Centers and Program Chairs</h3>

    <h4>Academic Advising</h4><p><b>Joe Spillane</b>&nbsp;&nbsp;<span class="email_chair">spillane@ufl.edu</span></p><h4>African American Studies</h4><p><b>Sharon Austin</b>&nbsp;&nbsp;<span class="email_chair">polssdw@polisci.ufl.edu</span></p><h4>African Studies</h4><p><b>Brenda Chalfin</b>&nbsp;&nbsp;<span class="email_chair">bchalfin@ufl.edu</span></p><h4>Bureau of Economic &amp; Business Research</h4><p><b>Christopher McCarty</b>&nbsp;&nbsp;<span class="email_chair">chrism@bebr.ufl.edu</span></p><h4>Dial Ctr Written &amp; Oral Comm</h4><p><b>Kellie Roberts</b>&nbsp;&nbsp;<span class="email_chair">robertsk@ufl.edu</span></p><h4>European Studies</h4><p><b>Amie Kreppel</b>&nbsp;&nbsp;<span class="email_chair">kreppel@ufl.edu</span></p><h4>France-florida Research INST</h4><p><b>Alioune Sow</b>&nbsp;&nbsp;<span class="email_chair">sow@ufl.edu</span></p><h4>Graham Center Public Service</h4><p><b>Matthew Jacobs</b>&nbsp;&nbsp;<span class="email_chair">mjacobs@ufic.ufl.edu</span></p><h4>Greek Studies</h4><p><b>Kostas Kapparis</b>&nbsp;&nbsp;<span class="email_chair">kapparis@ufl.edu</span></p><h4>Hindu Traditions</h4><p><b>Vasudha Narayanan</b>&nbsp;&nbsp;<span class="email_chair">vasu@ufl.edu</span></p><h4>Humanities and the Public Sphere</h4><p><b>Barbara Mennel</b>&nbsp;&nbsp;<span class="email_chair">mennel@ufl.edu</span></p><h4>International Studies</h4><p><b>Matthew Jacobs</b>&nbsp;&nbsp;<span class="email_chair">mjacobs@ufic.ufl.edu</span></p><h4>Jewish Studies</h4><p><b>Jack Kugelmass</b>&nbsp;&nbsp;<span class="email_chair">jkugelma@ufl.edu</span></p><h4>Land Use And Env. Change Institute</h4><p><b>Mark Brenner</b>&nbsp;&nbsp;<span class="email_chair">brenner@ufl.edu</span></p><h4>Samuel Proctor Oral History</h4><p><b>Paul Ortiz</b>&nbsp;&nbsp;<span class="email_chair">portiz@ufl.edu</span></p><h4>Teaching Center</h4><p><b>Robert Bailey</b>&nbsp;&nbsp;<span class="email_chair">rbailey3@ufl.edu</span></p><h4>University Writing Program</h4><p><b>Creed Greer</b>&nbsp;&nbsp;<span class="email_chair">cgreer@ufl.edu</span></p><h4>Women’s Studies</h4><p><b>Bonnie Moradi</b>&nbsp;&nbsp;<span class="email_chair">moradib@ufl.edu</span></p>
  
 </div><!-- chairs -->
