<h2>Articles</h2>

<h3>Online Education</h3>
<ul>
  <li><a href="https://www.insidehighered.com/digital-learning/article/2018/04/11/small-private-college-partners-pearson-go-national-online" target="_blank">The Next Southern New Hampshire?</a>, Inside Higher Ed, April 11, 2018</li>
  <li><a href="https://www.usnews.com/education/online-education/bachelors/rankings">Complete Online Bachelor’s Degree Rankings</a>, US News & World</li>
  <li><a href="https://www.usnews.com/education/online-learning-lessons/articles/2018-01-05/gain-skills-in-online-courses-requiring-group-work">Gain Skills in Online Curses Requiring Group Work</a>, US News & World Report </li>
  <li><a href="https://www.usnews.com/higher-education/online-education/articles/2018-01-18/4-expectations-for-online-education-in-2018">4 Expectations for Online Education in 2018</a>, US News & World Report</li>
  <li><a href="http://www.bestcolleges.com/features/cheapest-online-colleges/">The Most Affordable Online Colleges</a>, Best Colleges</li>
  <li><a href="https://www.insidehighered.com/digital-learning/article/2017/05/17/online-class-sizes-one-size-doesnt-fit-all" target="_blank">One Size Does Not Fit All</a>, Inside Higher Ed, May 17, 2017</li>
  <li><a href="https://www.insidehighered.com/quicktakes/2016/10/19/florida-system-plans-online-education-growth" target="_blank">Florida System Plans Online Education Growth</a>, Inside Higher Ed, October 19, 2016</li>
  <li><a href="http://www.sun-sentinel.com/news/education/sfl-florida-s-university-system-looks-to-boost-online-classes-20161018-story.html" target="_blank">Florida\'s university system looks to boost online classes</a>, SunSentinel, October 18, 2016</li>
  <li><a href="http://www.onlinecolleges.net/for-students/online-degrees-at-nonprofit-universities/" target="_blank">The Rise of the Online Degree at Public and Nonprofit Universities</a>, Center for Online Education</li>
  <li><a href="https://priceonomics.com/the-rise-of-the-online-degree-at-americas-top/" target="_blank">The Rise of the Online Degree at America\'s Top Universities</a>, Priceonomics.com</li>
  <li><a href="https://campustechnology.com/articles/2016/07/20/half-of-online-students-would-not-opt-for-live-courses.aspx" target="_blank">Half of Online Students Would Not Opt for Live Courses</a>, Campus Technology, July 20, 2016</li>
  <li><a href="http://www.learninghouse.com/ocs2016/" target="_blank">Online College Students Comprehensive Data on Demands and Preferences</a>, learninghouse.com</li>
  <li><a href="http://www.usnews.com/education/online-education/articles/2016-05-30/5-steps-for-veterans-to-choose-an-online-bachelors-program"  target="_blank">5 Steps for Veterans to Choose an Online Bachelor\'s Program</a>, US News &amp; World Report, May 30, 2016</li>
  <li><a href="http://www.ecampusnews.com/top-news/students-online-learning-277/" target="_blank">10 must-haves to appease online students</a>, eCampusNews, February 1, 2016</li>
  <li><a href="http://www.usnews.com/education/online-education/articles/2016-01-12/4-tips-for-adults-applying-to-top-online-bachelors-degree-programs" target="_blank">4 Tips for Adults Applying to Top Online Bachelor\'s Degree Programs</a>, US News &amp; World Report, January 12, 2016</li>
  <li><a href="https://www.insidehighered.com/views/2015/11/10/how-technology-needs-right-kind-leadership-create-transformative-change-essay?utm_source=Inside+Higher+Ed&utm_campaign=3dbb06ec55-DNU20151110&utm_medium=email&utm_term=0_1fcbc04421-3dbb06ec55-197322569#.VkHxkf8VIQY.mailto" target="_blank">Technology Is Not Enough</a>, Inside Higher Ed, November 10, 2015</li>
  <li><a href="https://medium.com/@cshirky/the-digital-revolution-in-higher-education-has-already-happened-no-one-noticed-78ec0fec16c7" target="_blank">The digital revolution in higher education has already happened. No one noticed.</a>, Clay Shirkey, Medium, November 6, 2015</li>
  <li><a href="http://www.usnews.com/education/online-education/articles/2015/10/07/online-education-not-just-for-nontraditional-students-anymore" target="_blank">Younger Students Drawn to Online Higher Education</a>, US News &amp; World Report, October 7, 2015</li>
  <li><a href="http://chronicle.com/article/Stirring-FearHope-U-of/231637/?cid=wc&utm_source=wc&utm_medium=en" target="_blank">Stirring Fear and Hope, U. of Akron Mulls an Aggressive Move Online</a>, The Chronical of Higher Education, July 15, 2015</li>
  <li><a href="http://chronicle.com/blogs/wiredcampus/an-increasingly-popular-job-perk-online-education/56771?cid=wc&utm_source=wc&utm_medium=en" target="_blank">An Increasingly Popular Job Perk: Online Education</a>, The Chronicle of Higher Education, June 3, 2015</li>
  <li><a href="http://hechingerreport.org/californias-multi-million-dollar-online-education-flop-is-another-blow-for-moocs/" target="_blank">California\'s multi-million dollar online education flop is another blow for MOOCs</a>, The Hechinger Report, April 14, 2015</li>
  <li><a href="http://www.npr.org/blogs/ed/2014/06/16/322402574/starbucks-will-pay-for-employees-to-complete-college" target="_blank">Starbucks Will Pay for Employees to Complete College</a>, NPR, June 16, 2014</li>
  <li><a href="http://www.academicimpressions.com/news/7-ways-advisors-can-more-effectively-engage-online-students" target="_blank">7 ways Advisors Can More Effectively Engage Online Students</a></li>
  <li><a href="http://campustechnology.com/articles/2014/02/26/average-tuition-for-an-online-bachelors-program-43477.aspx" target="_blank">Average Tuition for an Online Bachelor\'s Program: $43,477</a></li>
  <li><a href="http://www.usnews.com/education/online-education/bachelors/rankings" target="_blank">Best Online Bachelor\'s Programs (US News and World Report)</a></li>
  <li><a href="http://mfeldstein.com/open-data-case-study-ipeds/?utm_content=buffer3f3ae&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer" target="_blank">Open Data: A case study using IPEDS for online education</a></li>
  <li><a href="http://campustechnology.com/Articles/2014/01/29/The-Secret-of-Southern-New-Hampshire-Universitys-Success.aspx" target="_blank">The Secret of Southern New Hampshire University\'s Success</a>, (campustechnology.com)</li>
  <li><a href="http://money.cnn.com/2015/03/25/investing/university-of-phoenix-apollo-earnings-tank/index.html" target="_blank">University of Phoenix has lost half its students</a></li>
</ul>

<h3>UF Online</h3>
<ul>
  <li><a href="http://www.gainesville.com/news/20180430/first-uf-hybrid-students-to-graduate" target="_blank">First UF hybrid students to graduate</a>, The Gainesville Sun, April 30, 2018</li>
  <li><a href="https://www.insidehighered.com/digital-learning/article/2018/04/25/university-florida-onlineresidential-degree-program-sees-growing" target="_blank">University of Florida online/residential degree program sees growing interest as first class graduates</a>, Inside Higher Ed, April 25, 2018</li>
  <li><a href="http://www.alligator.org/news/first-students-to-graduate-from-pace-program-this-spring/article_48de3fd2-483a-11e8-9f2f-2bd996e50152.html" target="_blank">First 10 students to graduate from PaCE program this Spring</a>, The Alligator, April 25, 2018</li>
  <li><a href="https://www.usnews.com/higher-education/online-education/articles/2018-03-15/ask-4-questions-about-online-computer-science-degree-programs" target="_blank">Pick the Right Online Computer Science Degree Program</a>, U.S. News & World Report, March 15, 2018</li>
  <li><a href="http://www.gainesville.com/news/20180109/uf-online-ranks-12-nationwide" target="_blank">UF Online Ranks 12 Nationwide</a>, Gainesville Sun </li>
  <li><a href="http://www.alligator.org/news/article_50d2c1de-f747-11e7-a204-1f0852ddb672.html" target="_blank">Online Programs at UF Ranked Top in the Nation</a>, The Alligator</li>
  <li><a href="http://www.gainesville.com/news/20171214/uf-online-surpasses-1000-graduates" target="_blank">UF Online Surpasses 1000 Graduates</a>, Gainesville Sun</li>
  <li><a href="https://www.wuft.org/news/2017/11/21/uf-provides-opportunity-to-students-displaced-by-hurricanes/" target="_blank">UF Offers Online Classes To Displaced Puerto Rico Students</a>, WUFT 5</li>
  <li><a href="http://mfeldstein.com/remarkable-transformation-uf-online/" target="_blank">The Remarkable Transformation at UF Online</a>, e-Literate, November 29, 2016</li>
  <li><a href="http://www.usnews.com/education/online-education/articles/2016-05-30/5-steps-for-veterans-to-choose-an-online-bachelors-program" target="_blank">5 Steps for Veterans to Choose an Online Bachelor\'s Program</a>, US News &amp; World Report, May 30, 2016</li>
  <li><a href="https://www.insidehighered.com/quicktakes/2016/04/21/u-florida-online-students-get-access-campus-amenities" target="_blank">U of Florida Online Students Get Access to Campus Amenities</a>, Inside Higher Ed, April 21, 2016</li>
  <li><a href="http://www.gainesville.com/article/20160420/ARTICLES/160429959" target="_blank">Five things to know about optional fees for students in UF Online program</a>, Gainesville.com, April 20, 2016</li>
  <li><a href="http://www.orlandosentinel.com/features/education/school-zone/os-uf-bundle-package-story.html" target="_blank">Ordering higher education a la carte at University of Florida</a>, Orlando Sentinel, April 20, 2016</li>
  <li><a href="http://www.orlandosentinel.com/features/education/os-uf-online-only-student-20160212-story.html" target="_blank">UF\'s online-only students find early success</a>, Orlando Sentinel, February 12, 2016 (subscription required)</li>
  <li><a href="https://www.insidehighered.com/news/2015/10/23/less-two-years-after-launch-u-florida-reboots-online-education-initiative" target="_blank">UF Online Reboots</a>, Inside Higher Ed, October 23, 2015</li>
  <li><a href="http://chronicle.com/blogs/ticker/after-low-enrollment-u-of-florida-cancels-online-partnership-with-pearson" target="_blank">After Low Enrollment, U. of Florida Cancels Online Partnership With Pearson</a>, The Chronical of Higher Education, October 21, 2015</li>
  <li><a href="http://www.capitalnewyork.com/article/florida/2015/10/8580420/university-florida-set-cancel-contract-pearson-online-education" target="_blank">University of Florida set to cancel contract with Pearson for online education</a>, Politico Florida, October 21, 2015</li>
  <li><a href="http://gainesvillescene.com/uf-pace/" target="_blank">A Glimpse into the Mind of UF\'s First PaCE Student</a>, Gainesville Scene, October 1, 2015</li>
  <li><a href="http://chronicle.com/article/Facing-Online-Enrollment/233021/" target="_blank">Facing Online Enrollment Challenges, Florida Rethinks Pearson Partnership</a>, The Chronicle of Higher Education, September 11, 2015</li>
  <li><a href="http://college.usatoday.com/2015/07/10/florida-pace-program/" target="_blank">U. of Florida launches new, unconventional admission program</a>, USA Today, July 10, 2015</li>
  <li><a href="https://www.insidehighered.com/news/2015/06/11/u-florida-administrators-defend-controversial-new-admissions-program-pace" target="_blank">Gator from the Get-Go</a>, Inside HigherEd, June 11, 2015</li>
  <li><a href="http://www.tampabay.com/opinion/columns/column-uf-widens-access-with-online-learning/2233106" target="_blank">UF Widens Access with Online Learning</a>, Tampa Bay Times, June 10, 2015</li>
  <li><a href="http://www.wuft.org/news/2015/06/07/uf-pace-makes-it-difficult-for-biology-majors/" target="_blank">UF PaCE Complicates Applications To Professional Schools</a>, WUFT.org, June 7, 2015</li>
  <li><a href="http://mfeldstein.com/uf-online-and-enrollment-warning-signs/" target="_blank">UF Online and Enrollment Warning Signs</a>, e-Literate, May 28, 2015</li>
  <li><a href="http://www.tampabay.com/news/education/college/3100-high-school-seniors-told-welcome-to-uf-gator-nation-online-only/2224526" target="_blank">3,100 high school seniors told: Welcome to UF Gator Nation, online-only</a>, Tampa Bay Times, April 7, 2015</li>
  <li><a href="http://www.washingtonpost.com/blogs/answer-sheet/wp/2015/04/06/university-of-florida-admits-3000-students-then-tells-them-it-is-only-for-online-program/" target="_blank">"University of Florida Admits 3,000 Students - Then Tells Them It Is Only for Online Program"</a>, Washington Post, April 6, 2015</li>
  <li><a href="http://www.gainesville.com/article/20150328/ARTICLES/150329629/1002/news01?p=all&tc=pgall" target="_blank">UF Online struggling to meet enrollment expectations</a>, Gainesville Sun, March 28, 2015</li>			<li><a href="http://www.gainesville.com/article/20150327/articles/150329649" target="_blank">EPA exec picked to lead UF Online effort</a>, Gainesville Sun, March 27, 2015</li>
  <li><a href="http://www.gainesville.com/article/20150307/articles/150309704" target="_blank">For those who didn\'t make the cut, an alternative route to UF</a>, The Gainesville Sun, March 7, 2015</li>
  <li><a href="http://www.orlandosentinel.com/features/education/school-zone/os-uf-online-acceptance-post.html" target="_blank">UF Admits Some Students with a Catch</a>, Orlando Sentinel, February 16, 2015</li>
  <li><a href="https://www.insidehighered.com/news/2014/11/10/u-florida-political-science-department-declines-build-fully-online-degree" target="_blank">Saying No to Fully Online</a>, Inside Higher Ed, November 10, 2014</li>
  <li><a href="http://chronicle.com/article/What-You-Need-to-Know-About/149075/?cid=wc&utm_source=wc&utm_medium=en" target="_blank">What You Need to Know About Companies That Run Online Programs for Colleges, The Chronicle of Higher Education, September 30, 2014</a></li>
  <li><a href="https://www.insidehighered.com/news/2014/09/25/u-florida-online-considers-how-sell-studying-online-high-school-graduates" target="_blank">Going (But Not Going) to College</a>, Inside Higher Ed, September 25, 2014</li>
  <li><a href="http://www.gainesville.com/article/20140611/ARTICLES/140619972&tc=email_newsletter?p=1&tc=pg" target="_blank">UF Joins Online University Consortium</a>, Gainesville Sun, June 11, 2014</li>
  <li><a href="http://chronicle.com/article/Pushed-by-Lawmakers-U-of/146767/" target="_blank">Pushed by Lawmakers, U. of Florida Dives into Online Education</a>, The Chronicle of Higher Education, May 23, 2014</li>
  <li><a href="http://campustechnology.com/articles/2014/02/04/u-florida-targets-24000-online-enrollments-through-pearson-partnership.aspx" target="_blank">U Florida Targets 24,000 Online Enrollments Through Pearson Partnership</a>, February 4, 2014</li>
  <li><a href="http://mfeldstein.com/uf-online-what-it-is-and-isnt/" target="_blank">UF Online: What it is and what it isn\'t</a> (e-Literate, 2/18/14)</li>
</ul>

<h3>UF Online Corporate Partnerships</h3>
<ul>
  <li><a href="https://www.gainesville.com/news/20180904/disney-joins-uf-online-roster" target="_blank">Disney Joins UF Online Roster</a>, Gainesville Sun, Sept. 4, 2018</li>
  <li><a href="http://www.orlandosentinel.com/business/tourism/os-cfb-disney-uf-20180904-story.html" target="_blank">UF: Disney Workers Can Study Everything from Business to Sports Management Under New Program</a>, Orlando Sentinel, Sept. 4, 2018</li>
  <li><a href="https://ufonline.ufl.edu/news/uf-online-welcomes-disney-into-employer-pathways/" target="_blank">/UF Online Welcomes Disney into Employer Pathways</a>, UF Online News, Sept. 4, 2018</li>
  <li><a href="http://news.ufl.edu/articles/2018/05/uf-to-partner-with-walmart-in-new-education-benefit-for-associates.php" target="_blank">UF to partner with Walmart in new education benefit for associates</a>, UF News, May 30, 2018</li>
  <li><a href="https://www.bloomberg.com/news/articles/2018-05-30/walmart-offers-to-foot-college-tuition-bills-for-u-s-employees" target="_blank">Walmart Offers to Foot College Tuition Bills for U.S. Employees</a>, Bloomberg.com, May 30, 2018</li>
  <li><a href="https://www.orlandoweekly.com/Blogs/archives/2018/05/30/walmart-workers-can-soon-earn-a-degree-from-university-of-florida-for-1-a-day" target="_blank">Walmart workers can soon earn a degree from University of Florida for $1 a day</a>, Orlando Weekly, May 30, 2018</li>
  <li><a href="http://www.tampabay.com/news/education/college/Walmart-employees-can-now-get-a-University-of-Florida-diploma-for-1-per-day_168705997 " target="_blank">Walmart employees can now get a University of Florida diploma for $1 per day</a>, Tampa Bay Times, May 30, 2018</li>
  <li><a href="https://www.wtsp.com/article/news/education/university-of-florida-to-offer-walmart-employees-online-degree-for-1-per-day/67-559844574" target="_blank">University of Florida to offer Walmart employees online degree for $1 per day</a>, 10 News WTSP (CBS Tampa), May 30, 2018</li>
  <li><a href="https://www.apnews.com/e649e59888274e0c9052df2c1ea63cc5/Walmart-offers-employees-new-perk:-cheap-access-to-college" target="_blank">Walmart offers employees new perk: cheap access to college</a>, Associated Press - AP Wire, May 30, 2018</li>
  <li><a href="https://www.washingtonpost.com/news/business/wp/2018/05/30/walmart-to-offer-employees-a-college-education-for-1-a-day/?utm_term=.6df334611164." target="_blank">Walmart to offer employees a college education for $1 a day</a>, Washington Post, May 30, 2018</li>
  <li><a href="https://www.al.com/news/index.ssf/2018/05/walmart_employees_eligible_for.html" target="_blank">Walmart employees eligible for $1-per-day college tuition </a>, Alabama.com, May 30, 2018</li>
  <li><a href="http://www.gainesville.com/news/20180530/uf-online-walmart-offer-workers-education-plan" target="_blank">UF Online-Walmart offer workers’ education plan</a>, Gainesville Sun, May 30, 2018</li>
  <li><a href="https://www.edsurge.com/news/2018-05-30-walmart-chooses-three-colleges-where-its-employees-can-study-for-1-a-day" target="_blank">Walmart Chooses Three Colleges Where Its Employees Can Study For $1 a Day</a>, EdSurge, May 30, 2018</li>
  <li><a href="https://www.reddit.com/r/ufl/comments/8nab0x/uf_online_providing_business_degrees_to_walmart/" target="_blank">UF online providing business degrees to Walmart employees</a>, UFL Reddit, May 30, 2018</li>
  <li><a href="http://www.businessinsider.com/walmart-college-education-employees-2018-5" target="_blank">Walmart is now offering college tuition to employees for $1 a day</a>, Business Insider, May 30, 2018</li>
  <li><a href="https://www.wsj.com/articles/walmart-to-pay-college-costs-for-its-u-s-store-workers-1527706190" target="_blank">Walmart to pay certain college costs for US workers</a>, Wall Street Journal, May 30, 2018</li>
  <li><a href="https://www.washingtonexaminer.com/business/walmart-to-cover-employees-college-tuition-within-limits" target="_blank">Walmart to cover employees\' college tuition, within limits</a>, Washington Examiner, May 30, 2018</li>
  <li><a href="http://fortune.com/2018/05/30/walmart-paying-college-tuition-for-employees/" target="_blank">Walmart Offers to Pay College Tuition Bills for U.S. Employees</a>, Fortune.com, May 30, 2018</li>
  <li><a href="http://adage.com/article/cmo-strategy/walmart-s-employer-brand-offer-pay-collage/313680/" target="_blank">Walmart has a new employer brand - and an offer to pay for college</a>, AdAge, May 30, 2018</li>
  <li><a href="http://money.cnn.com/2018/05/30/pf/college/walmart-tuition-benefit/index.html" target="_blank">Walmart’s perk for workers: Go to college for $1 a day</a>, CNN Money , May 30, 2018</li>
  <li><a href="https://www.denverpost.com/2018/05/30/walmart-guild-education-college-degree-program/" target="_blank">Walmart employees can now earn a college degree thanks to this Denver partnership </a>, Denver Post, May 30, 2018</li>
  <li><a href="https://www.cnbc.com/2018/05/30/walmart-unveils-a-new-employee-perk-college-tuition.html" target="_blank">Walmart unveils a new employee perk: College tuition</a>, CNBC, May 30, 2018</li>
  <li><a href="http://www.masslive.com/business-news/index.ssf/2018/05/walmart_offers_college_tuition_to_employ.html" target="_blank">Walmart offers college tuition to employees for $1 a day</a>, Mass Live, May 31, 2018</li>
</ul>
