<?php
$i = 0;

$sites_clasTheme_prod = array(
  "/aiis/",
  "/astronomy/",
  "/augment/",
  "/biology-fraser/",
  "/clas-advancement/",
  "/clas-comms/",
  "/clascomtemplate/",
  "/clas-dean/",
  "/clas-dsc/",
  "/clas-PHPB/",
  "/clas-recognition-ceremony/",
  "/clas-researchoffice/",
  "/classc/",
  "/classics-garden-conference/",
  "/collegechampions/",
  "/economics/",
  "/electionscience/",
  "/english/",
  "/english-comics/",
  "/english-cw/",
  "/english-film/",
  "/english-imagetext/",
  "/english-ipsa/",
  "/EnglishLanguageInstitute/",
  "/geology/",
  "/globalislam/",
  "/history/",
  "/history-capitalism/",
  "/humanities/",
  "/humanities-ethics-in-the-public-sphere/",
  "/humanities-grants/",
  "/jewish-studies/",
  "/languagestudio/",
  "/math/",
  "/math-narg/",
  "/mediaservices/",
  "/phil-aiethics/",
  "/physics-efrc/",
  "/physics-scinews/",
  "/polisci/",
  "/psych-sourcesofstrength/",
  "/soccrim/",
  "/songs/",
  "/spanishportuguese/",
  "/spohp/",
  "/spohp-ogus/",
  "/Stat-Club/",
  "/stat-fass/",
  "/sustainability/",
  "/ums/",
  "/vrsocialgood/",
  "/writing/"
);



$sites_clasTheme_test = array(
  "/advising/"               => 8,
  "/biology/"                => 6,
  "/biology-test/"           => 0,
  "/ces/"                    => 6,
  "/clas-news/"              => 9,
  "/classc/"                 => 6,
  "/commsTemplateTest/"      => 0,
  "/communicationstemplate/" => 0,
  "/electionscience/"        => 5,
  "/english/"                => 5,
  "/english-cclc/"           => 7,
  "/english-cw/"             => 4,
  "/english-fms/"            => 4,
  "/english-imagetext/"      => 0,
  "/english-ipsa/"           => 4,
  "/ethics-public/"          => 6,
  "/franceflorida/"          => 4,
  "/geology/"                => 6,
  "/history/"                => 7,
  "/history-capitalism/"     => 0,
  "/humanities/"             => 6,
  "/humanities-grants/",
  "/jonsTestSite/",
  "/jst/",
  "/languages/",
  "/linguistics/",
  "/math/",
  "/mathtest/",
  "/philosophy/",
  "/phys-ccms/",
  "/phys-cmt/",
  "/physics-het/",
  "/physics-ift/",
  "/physics-qtp/",
  "/phys-ihepa/",
  "/polisci/",
  "/psych-wellness/",
  "/sanibel-symposium/",
  "/songs/",
  "/spanport/",
  "/spohp-ogus/",
  "/stat-dc/",
  "/stat-fass/",
  "/sustainability/",
  "/unittest/",
  "/writing/"
);

  foreach ($sites_clasTheme_test as $key) {
    $i++;
  }

?>
